package forge.llm.opencode;

import java.io.File;
import java.io.IOException;
import java.net.ServerSocket;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.HexFormat;
import java.util.List;
import java.util.Map;
import java.util.stream.Stream;

import org.tinylog.Logger;

/**
 * An {@code opencode serve} process owned by this JVM. It listens on a free loopback port behind a random
 * password, is started with a configuration generated by {@link OpencodeConfigBuilder} and, when
 * {@link OpencodeSettings#isolate} is set, with private config/data/state/cache directories so that it never
 * reads or modifies the user's own opencode setup. It is killed (with its child processes) on {@link #close()}
 * and when the JVM exits.
 */
public final class OpencodeServer implements AutoCloseable {
    private final Process process;
    private final Path workDir;
    private final Path logFile;
    private final String baseUrl;
    private final String password;
    private final boolean deleteWorkDir;
    private final Thread shutdownHook;
    private volatile boolean closed;

    private OpencodeServer(Process process, Path workDir, Path logFile, String baseUrl, String password, boolean deleteWorkDir) {
        this.process = process;
        this.workDir = workDir;
        this.logFile = logFile;
        this.baseUrl = baseUrl;
        this.password = password;
        this.deleteWorkDir = deleteWorkDir;
        this.shutdownHook = new Thread(this::close, "opencode-shutdown");
        Runtime.getRuntime().addShutdownHook(shutdownHook);
    }

    public String baseUrl() {
        return baseUrl;
    }

    public String username() {
        return "opencode";
    }

    public String password() {
        return password;
    }

    public Path logFile() {
        return logFile;
    }

    /** Starts opencode and waits until it answers its health check. */
    public static OpencodeServer start(OpencodeSettings s) {
        final String config = OpencodeConfigBuilder.build(s).toString();
        final boolean tempDir = s.workDir == null;
        if (tempDir) {
            sweepStaleWorkDirs();
        }
        final Path workDir;
        try {
            workDir = tempDir ? Files.createTempDirectory(WORK_DIR_PREFIX) : Files.createDirectories(s.workDir);
            Files.createDirectories(workDir.resolve("project"));
        } catch (IOException e) {
            throw new OpencodeException("cannot create the opencode working directory", e);
        }

        final int port = freePort();
        final String password = randomPassword();
        final List<String> command = new ArrayList<>(executable(s));
        command.addAll(List.of("serve", "--port", String.valueOf(port), "--hostname", "127.0.0.1", "--pure"));
        if (s.logLevel != null) {
            command.addAll(List.of("--print-logs", "--log-level", s.logLevel));
        }

        final ProcessBuilder pb = new ProcessBuilder(command);
        pb.directory(workDir.resolve("project").toFile());
        final Map<String, String> env = pb.environment();
        env.put("OPENCODE_SERVER_PASSWORD", password);
        env.put("OPENCODE_CONFIG_CONTENT", config);
        // Variables of the user's shell that would redirect or reconfigure the server we are about to start.
        env.remove("OPENCODE_SERVER_USERNAME"); // the client always authenticates as "opencode"
        env.remove("OPENCODE_CONFIG");
        env.remove("OPENCODE_CONFIG_DIR");
        if (s.isolate) {
            // opencode also reads Claude Code's ~/.claude/CLAUDE.md and every AGENTS.md/CLAUDE.md/opencode.json it
            // finds from the working directory upwards, and appends them to the system prompt of every request.
            // None of that belongs in a card game, and it would be sent to whatever provider is in use.
            env.put("OPENCODE_DISABLE_CLAUDE_CODE", "1");
            env.put("OPENCODE_DISABLE_PROJECT_CONFIG", "1");
            for (String dir : List.of("config", "data", "state")) {
                try {
                    Files.createDirectories(workDir.resolve("xdg").resolve(dir));
                } catch (IOException e) {
                    throw new OpencodeException("cannot create " + dir + " directory for opencode", e);
                }
            }
            env.put("XDG_CONFIG_HOME", workDir.resolve("xdg").resolve("config").toString());
            env.put("XDG_DATA_HOME", workDir.resolve("xdg").resolve("data").toString());
            env.put("XDG_STATE_HOME", workDir.resolve("xdg").resolve("state").toString());
            // Caches (downloaded provider SDKs, model list) are not private data and are slow to rebuild: keep them
            // between runs instead of re-downloading on every start.
            env.put("XDG_CACHE_HOME", sharedCacheDir().toString());
        }
        final Path log = workDir.resolve("opencode.log");
        pb.redirectErrorStream(true);
        pb.redirectOutput(log.toFile());

        final Process process;
        try {
            process = pb.start();
        } catch (IOException e) {
            if (tempDir) {
                deleteQuietly(workDir);
            }
            throw new OpencodeException("cannot start '" + String.join(" ", command)
                    + "' - is opencode installed and on the PATH (or is --oc-exe right)?", e);
        }
        final OpencodeServer server = new OpencodeServer(process, workDir, log, "http://127.0.0.1:" + port, password, tempDir);
        try {
            server.awaitHealthy(s.startupTimeoutSeconds);
        } catch (RuntimeException e) {
            server.close();
            throw e;
        }
        Logger.info("opencode server up at {} (log: {})", server.baseUrl, log);
        return server;
    }

    private void awaitHealthy(int timeoutSeconds) {
        final OpencodeClient probe = new OpencodeClient(baseUrl, username(), password);
        final long deadline = System.nanoTime() + timeoutSeconds * 1_000_000_000L;
        while (System.nanoTime() < deadline) {
            if (!process.isAlive()) {
                throw new OpencodeException("opencode exited during startup (exit code " + process.exitValue() + "):\n" + tail(logFile));
            }
            if (probe.isHealthy()) {
                return;
            }
            try {
                Thread.sleep(300);
            } catch (InterruptedException e) {
                Thread.currentThread().interrupt();
                throw new OpencodeException("interrupted while waiting for opencode to start", e);
            }
        }
        throw new OpencodeException("opencode did not become healthy within " + timeoutSeconds + "s:\n" + tail(logFile));
    }

    @Override
    public synchronized void close() {
        if (closed) {
            return;
        }
        closed = true;
        try {
            Runtime.getRuntime().removeShutdownHook(shutdownHook);
        } catch (IllegalStateException ignored) {
            // JVM is already shutting down
        }
        // the launcher may be a shim (opencode.cmd -> cmd.exe -> opencode.exe): take down everything it started
        final List<ProcessHandle> family = new ArrayList<>();
        process.descendants().forEach(family::add);
        family.add(process.toHandle());
        family.forEach(ProcessHandle::destroyForcibly);
        try {
            for (ProcessHandle p : family) {
                p.onExit().get(5, java.util.concurrent.TimeUnit.SECONDS); // files stay locked until the process is gone
            }
        } catch (InterruptedException e) {
            Thread.currentThread().interrupt();
        } catch (java.util.concurrent.ExecutionException | java.util.concurrent.TimeoutException ignored) {
            // best effort
        }
        if (deleteWorkDir) {
            for (int attempt = 0; attempt < 3 && Files.exists(workDir); attempt++) {
                deleteQuietly(workDir);
                if (Files.exists(workDir)) {
                    try {
                        Thread.sleep(500);
                    } catch (InterruptedException e) {
                        Thread.currentThread().interrupt();
                        break;
                    }
                }
            }
        }
    }

    // ---- helpers ---------------------------------------------------------------------------------------

    /** The command that launches opencode: resolved against the PATH, with the extensions Windows uses. */
    static List<String> executable(OpencodeSettings s) {
        final String name = s.executable == null ? "opencode" : s.executable;
        final File direct = new File(name);
        if (direct.isFile()) {
            return List.of(direct.getAbsolutePath());
        }
        final boolean windows = System.getProperty("os.name", "").toLowerCase().contains("win");
        final String[] extensions = windows ? new String[] {".cmd", ".exe", ".bat", ""} : new String[] {""};
        final String path = System.getenv("PATH");
        if (path != null) {
            for (String dir : path.split(File.pathSeparator)) {
                for (String ext : extensions) {
                    final File candidate = new File(dir, name + ext);
                    if (candidate.isFile()) {
                        return List.of(candidate.getAbsolutePath());
                    }
                }
            }
        }
        return List.of(name); // let the OS try; the error message then names what was attempted
    }

    private static final String WORK_DIR_PREFIX = "forge-llm-opencode";
    private static final long STALE_AFTER_MILLIS = 24L * 60 * 60 * 1000;

    private static Path sharedCacheDir() {
        try {
            return Files.createDirectories(Path.of(System.getProperty("java.io.tmpdir"), WORK_DIR_PREFIX + "-cache"));
        } catch (IOException e) {
            throw new OpencodeException("cannot create the opencode cache directory", e);
        }
    }

    /** Work directories of runs that were killed before they could clean up (they hold session history). */
    private static void sweepStaleWorkDirs() {
        final File tmp = new File(System.getProperty("java.io.tmpdir"));
        final File[] dirs = tmp.listFiles((d, name) -> name.startsWith(WORK_DIR_PREFIX) && !name.equals(WORK_DIR_PREFIX + "-cache"));
        if (dirs == null) {
            return;
        }
        for (File dir : dirs) {
            if (dir.isDirectory() && System.currentTimeMillis() - dir.lastModified() > STALE_AFTER_MILLIS) {
                deleteQuietly(dir.toPath());
            }
        }
    }

    private static int freePort() {
        try (ServerSocket socket = new ServerSocket(0, 1, java.net.InetAddress.getLoopbackAddress())) {
            return socket.getLocalPort();
        } catch (IOException e) {
            throw new OpencodeException("no free local port for opencode", e);
        }
    }

    private static String randomPassword() {
        final byte[] bytes = new byte[18];
        new SecureRandom().nextBytes(bytes);
        return HexFormat.of().formatHex(bytes);
    }

    private static String tail(Path file) {
        try {
            final List<String> lines = Files.readAllLines(file, StandardCharsets.UTF_8);
            return String.join("\n", lines.subList(Math.max(0, lines.size() - 25), lines.size()));
        } catch (IOException | RuntimeException e) {
            return "(no log)";
        }
    }

    private static void deleteQuietly(Path dir) {
        try (Stream<Path> files = Files.walk(dir)) {
            files.sorted(java.util.Comparator.reverseOrder()).forEach(p -> p.toFile().delete());
        } catch (IOException | RuntimeException ignored) {
            // temp files; the OS will clean up eventually
        }
    }
}
